# Generated by Django 4.2.29 on 2026-04-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrpay', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRTransaction',
        ),
    ]
