# Generated by Django 6.0.3 on 2026-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qrpay', '0002_delete_qrtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qris_number', models.CharField(max_length=255, unique=True)),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_PT', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
