# Generated by Django 6.0.3 on 2026-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrpay', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qris',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qris',
            name='transaction_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
