# Generated by Django 4.2.29 on 2026-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='kusaku_points',
            field=models.IntegerField(default=0),
        ),
    ]
