# Generated by Django 4.2.29 on 2026-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_expense_kusaku_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receiver',
            field=models.CharField(default='category', max_length=255),
        ),
    ]
