# Generated by Django 4.2.29 on 2026-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybudget',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='categorybudget',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
